[package]
name = "merc_pest_consume_macros"
version = "2.0.0"
license = "MIT OR Apache-2.0"
description = "Macros for pest_consume"
readme = "README.md"
keywords = ["pest", "parser", "peg", "grammar", "proc_macro"]
categories = ["parsing"]
edition.workspace = true
repository.workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
quote.workspace = true
proc-macro2.workspace = true
syn.workspace = true
