[package]
name = "merc_tools"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
merc_utilities.workspace = true

clap.workspace = true
log.workspace = true
winapi.workspace = true
